include:
  - file: "/build/golang/template-app-go.yml"
    project: "platform/pipelines-templates"
    ref: "master"

default:
  image: golang:1.23

variables:
  IMAGE_NAME: mia_template_image_name_placeholder